# GitHub Actions: Job Artifacts Configuration

name: "📦 [Workflow-16] Job Artifacts Configuration"

run-name: "📦 [Workflow-16] ${{ github.actor }} → Sharing Build Artifacts Between Jobs"

env : 
  APP_ARTIFACT_NAME : "Node-JS App Build File"
on : 
  push : 
    branches : [develop,master]
    paths:
      - '.github/workflows/16-Job-Artifacts-Configuration-CI.yml'
      - '16-Job-Artifacts-Configuration-CI-Workflow/**'

jobs : 
  upload-artifact-job :
    name : Node-Js Upload Artifacts Job

    runs-on :  ubuntu-latest

    env : 
      NODE_VERSION : '24'
    steps : 
      - name : Checkout the Repository
        uses : actions/checkout@v6

      - name :  Setup Node JS Environment
        uses : actions/setup-node@v7
        with : 
          node-version : ${{env.NODE_VERSION}}
      
      - name : Install Depenedency and Build
        run : |
          echo "Running the NOde Js App Before the Upload Artifacts uplod !!!"
          npm install
          npm run build
      
      - name : Upload App Artifacts 
        uses : actions/upload-artifact@v4
        with :
          name : ${{env.APP_ARTIFACT_NAME}}
          path : |
           package.json
           build.js
  
  download-artifact-job : 
    name : Node Js Download Artifacts Job

    runs-on :  ubuntu-latest

    needs : upload-artifact-job

    env :
      NODE_VERSION : '24'

    steps : 
      - name : Download App Artifacts
        uses : actions/download-artifact@v4
        with : 
          name : ${{env.APP_ARTIFACT_NAME}}

      - name : Setup the Node JS Environment
        uses : actions/setup-node@v7
        with : 
          node-version : ${{env.NODE_VERSION}}
      
      - name : Run the Artifacts Code Files
        run : |
          npm install
          npm run build
